hostname = us-central1-alight-creative.cloudfunctions.net

^https?:\/\/us-central1-alight-creative\.cloudfunctions\.net\/getAccountStatusAndLicenses url script-response-body https://raw.githubusercontent.com/GenzPN-Company-Limited/GenzPN-Proxy/main/js/quantumult_x/alightmotion.js